@startuml "Практическая работа 2-2"
left to right direction
title Система автоматического тестирования: диаграмма развертывания
skinparam backgroundcolor AntiqueWhite/Grey
database Тестирования
node ПК_Пользователь
node ПК_Программное_обеспечение
node Тестовые_данные
node Система_тестирования
ПК_Пользователь - Тестовые_данные: Выдаёт
ПК_Программное_обеспечение - Тестовые_данные: Использует
ПК_Программное_обеспечение - Тестирования: Выполняет
ПК_Пользователь - Система_тестирования: Проверка выполнения тестирования
Система_тестирования - Тестирования
@enduml
