@startuml "Практическая работа 2.1"
title Система автоматического тестирования: диаграмма последовательности
skinparam backgroundcolor AntiqueWhite/Grey
participant Пользователь
participant Тестирование
participant Программное_обеспечение
participant Таймер
activate Пользователь
Пользователь -> Тестирование: Определяет тестовые данные
activate Тестирование
Пользователь -> Программное_обеспечение: Выдает тестовые данные
deactivate Пользователь
activate Программное_обеспечение
Программное_обеспечение -> Таймер:Включает таймер для отслеживания времени
activate Таймер
Программное_обеспечение -> Тестирование:Приступает к выполнению тестирования
Программное_обеспечение -> Тестирование:Выполняет тестирование
deactivate Тестирование
Программное_обеспечение -> Таймер:Закрепляет время выполнения
deactivate Таймер
Программное_обеспечение -> Пользователь:Выводит результаты тестирования
deactivate Программное_обеспечение
activate Пользователь
activate Тестирование
Пользователь -> Тестирование:Анализирует результаты тестирования
deactivate Пользователь
deactivate Тестирование
@enduml
