@startuml "Практическая работа 0"
left to right direction
rectangle Гейм-дев_отдел{
Дизайнер -- (Создание концепта)
Руководитель -- (Согласование концепта)
Руководитель -- (Согласование модели)
(Одобрение концепта) <. (Согласование концепта)
(Согласование концепта) <.. (Создание концепта)
3D_моделлер -- (Создание модели)
(Создание модели) <. (Одобрение концепта)
(Согласование модели) <.. (Создание модели)
(Одобрение модели) <. (Согласование модели)
Аниматор -- (Анимирование модели)
(Анимирование модели) <. (Одобрение модели)
}
@enduml
