@startuml "Практическая работа 1-1"
left to right direction
title Система автоматического тестирования
actor Пользователь
actor ПО_автоматизированного_тестирования
rectangle Система {
Пользователь -- (Определение тестовых данных)
(Определение тестовых данных) ..>(Выполнение тестирования):<<include>>
(Определение тестовых данных) ..> (Сопровождение тестирования):<<include>>
ПО_автоматизированного_тестирования -- (Выполнение тестирования)
(Выполнение тестирования) ..>(Сбор статистики выполнения):<<include>>
(Сбор статистики выполнения) ..> (Оценка результатов выполнения):<<include>>
(Сопровождение тестирования) ..> (Оценка результатов выполнения):<<include>>
}
@enduml


@startuml "Практическая работа 1-2"
class Пользователь{
Определение тестовых данных()
Отслеживание тестирования()
Анализ результатов()
}
class ПО_автоматизированного_тестирования{
Приём тестовых данных()
Выполнение тестирования()
Вывод результаты выполнения()
}
class Тестовые_данные{
+Тестовые данные
}
class Тестирование{
+Номер тестирования
+Время выполнения тестирования
}
class Результаты{
+Номер тестирования
+Результаты тестирования
}
Пользователь --> Тестовые_данные:Определяет
ПО_автоматизированного_тестирования --> Тестовые_данные:Принимает
ПО_автоматизированного_тестирования --> Тестирование:Выполняет
ПО_автоматизированного_тестирования --> Результаты:Выводит
Пользователь --> Тестирование:Отслеживает
Пользователь --> Результаты:Анализирует
Тестовые_данные ..> Тестирование
Тестирование ..> Результаты
