@startuml "Практическая работа 1"
left to right direction
title Система автоматического тестирования
actor Пользователь
actor ПО_автоматизированного_тестирования

rectangle Система {
Пользователь -- (Определение тестовых данных)
(Определение тестовых данных) ..>(Выполнение тестирования):<<include>>
(Определение тестовых данных) ..> (Сопровождение тестирования):<<include>>
ПО_автоматизированного_тестирования -- (Выполнение тестирования)
(Выполнение тестирования) ..>(Сбор статистики выполнения):<<include>>
(Сбор статистики выполнения) ..> (Оценка результатов выполнения):<<include>>
(Сопровождение тестирования) ..> (Оценка результатов выполнения):<<include>>
}
@enduml
